name: Deploy to OVH

on:
  push:
    branches:
      - main  # Déploie à chaque push sur la branche main

jobs:
  ftp-deploy:
    name: Deploy website via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"  # Dossier à envoyer (ajuste si nécessaire)
          server-dir: "/"  # Dossier distant sur OVH (ajuste selon ton arborescence)
          protocol: ftp
